### ISSUE TITLE
cannot apply the theme

### ISSUE THREAD

**Issue by gj1118** [ihodev/sublime-da-ui#1]
I extracted the package to the packages folder. The options present
themselves in ST but after that nothing works.
Extracted package : https://cl.ly/mbit
Error : https://cl.ly/maup
Can you please let me know what I am doing wrong ?
I am on latest mac on latest ST Dev build.

**Comment by gj1118** [comment]
I got it working .. looks extremely nice .. Thanks

**Comment by ihodev** [comment]
That's because the name of the package `DA UI`, you have to rename it from `DAUI` to `DA UI`. The result folder name should be `Packages/DA UI/<contents>`. I'm glad you like it :wink:
