### ISSUE TITLE
How to enable light theme like in GIF on readme?

### ISSUE THREAD

**Issue by niceque** [ihodev/sublime-da-ui#17]
Thanks!

**Comment by niceque** [comment]
Found in color schemes. Can be closed.

**Comment by ihodev** [comment]
Some color schemes from GIF can be found in [DACS](https://github.com/ihodev/sublime-da-cs) package.
It will be available [soon](https://github.com/wbond/package_control_channel/pull/6630) on Package Control. Currently you can install it manually.

P.S. Thanks for the issue, I'll improve `Get It` section.
