### ISSUE TITLE
Disable colored title bars by default due to random high CPU usage

### ISSUE THREAD

**Issue by swashata** [ihodev/sublime-da-ui#30]
When using DA UI theme, sometimes the CPU usage is very high. Usually at 50-60% making sublime very less responsive. When using the default Adaptive Theme (with the DA CS color scheme) it works just fine. But when using DA UI theme, the CPU usage spikes.

## Expected Behavior

The CPU usage should stay same/similar.

## Current Behavior

CPU is spiking. I have already tried with the following workarounds.

1. Disable Indexing.
2. Disable plugins.

## Possible Solution

The workaround is to select the default adaptive theme > restart sublime and then select DA theme. Then the CPU stays within normal limit.

Also it isn't always consistent. Maybe this is a theming engine bug from ST. This happens all of a sudden, and sometimes restarting computer helps.

## Steps to Reproduce

1. Install DA UI theme and from command pallet, select DA.
2. Close sublime (`opt+Q`).
3. Start sublime again.

## Your Environment

<div class="section">
  <h3 class="section__title">Environment Details</h3>
  <ul class="list">
    <li class="list__item">
      <b>Platform</b>: Osx
    </li>
    <li class="list__item">
      <b>Sublime Text</b>: 3153
    </li>
    <li class="list__item">
      <b>DA UI</b>: 1.0.0-beta.1.2
    </li>
    <li class="list__item">
      <b>Installed via Package Control</b>: True
    </li>
    <li class="list__item">
      <b>A File Icon is Installed</b>: True
    </li>
  </ul>
</div>
<div class="section">
  <h3 class="section__title">User Settings</h3>
  <div class="section">
    <h4 class="section__title">UI Theme</h4>
    <pre>{
  "accent_color": "#ffcc66",
  "font_face": "Operator Mono SSm Light",
  "skin":
  {
    "id": "origin",
    "settings":
    {
    }
  }
}
</pre>
  </div>
  <div class="section">
    <h4 class="section__title">Color Scheme</h4>
    <pre>{
  "accent_color": "#ffcc66"
}
</pre>
  </div>
  <div class="section">
    <h4 class="section__title">Sublime Text</h4>
    <pre>{
  "always_show_minimap_viewport": true,
  "atomic_save": false,
  "auto_complete": true,
  "auto_complete_commit_on_tab": true,
  "binary_file_patterns":
  [
    "generated/*",
    "*.tbz2",
    "*.gzip",
    "*.jpg",
    "*.jpeg",
    "*.png",
    "*.gif",
    "*.ttf",
    "*.tga",
    "*.dds",
    "*.ico",
    "*.eot",
    "*.pdf",
    "*.swf",
    "*.jar",
    "*.zip",
    "node_modules/",
    "node_build/",
    "vendor/"
  ],
  "bold_folder_labels": true,
  "caret_extra_bottom": 1,
  "caret_extra_top": 1,
  "caret_extra_width": 1,
  "caret_style": "blink",
  "close_windows_when_empty": true,
  "color_scheme": "Packages/DA CS/Tomorrow Dark.tmTheme",
  "css.gradient.fallback": true,
  "default_font_size": 12,
  "default_line_ending": "unix",
  "detect_indentation": false,
  "disable_tab_abbreviations": true,
  "enable_tab_scrolling": true,
  "ensure_newline_at_eof_on_save": true,
  "fade_fold_buttons": false,
  "file_exclude_patterns":
  [
    "*.pyc",
    "*.pyo",
    "*.exe",
    "*.dll",
    "*.obj",
    "*.o",
    "*.a",
    "*.lib",
    "*.so",
    "*.dylib",
    "*.ncb",
    "*.sdf",
    "*.suo",
    "*.pdb",
    "*.idb",
    ".DS_Store",
    "*.class",
    "*.psd",
    "*.db",
    "*.sublime-workspace"
  ],
  "folder_exclude_patterns":
  [
    ".svn",
    ".git",
    ".hg",
    "CVS",
    "build"
  ],
  "font_face": "Operator Mono SSm Lig Book",
  "font_size": 14,
  "highlight_line": true,
  "highlight_modified_tabs": true,
  "ignored_packages":
  [
    "JavaScript",
    "Vintage",
    "Vuejs Complete Package"
  ],
  "indent_guide_options":
  [
    "draw_normal",
    "draw_active"
  ],
  "indent_to_bracket": true,
  "index_exclude_patterns":
  [
    "*.log",
    "node_modules/",
    "node_build/",
    "vendor/"
  ],
  "index_files": true,
  "line_padding_bottom": 4,
  "line_padding_top": 4,
  "match_brackets": false,
  "match_brackets_angle": false,
  "match_brackets_braces": false,
  "match_brackets_content": false,
  "match_brackets_square": false,
  "match_tags": false,
  "mouse_wheel_switches_tabs": true,
  "overlay_scroll_bars": "enabled",
  "rulers":
  [
    80
  ],
  "save_on_focus_lost": false,
  "shift_tab_unindent": true,
  "show_definitions": false,
  "show_encoding": true,
  "show_full_path": true,
  "show_line_endings": true,
  "show_navigation_bar": false,
  "skin": "DA UI/Origin",
  "sublimelinter_popup_errors_on_save": true,
  "tab_size": 4,
  "theme": "DA.sublime-theme",
  "translate_tabs_to_spaces": false,
  "trim_automatic_white_space": true,
  "trim_trailing_white_space_on_save": true,
  "word_separators": "./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}`~?"
}
</pre>
  </div>
  <div class="section">
  <h4 class="section__title">Installed Packages</h4>
  <pre>{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"A File Icon",
		"AlignTab",
		"Bootstrap 3 Snippets",
		"BracketHighlighter",
		"Clipboard Manager",
		"DA CS",
		"DA UI",
		"DocBlockr_with_update_capability",
		"Dockerfile Syntax Highlighting",
		"EditorConfig",
		"Emmet",
		"Gitignore",
		"Idiomatic-CSS-Comments-Snippets",
		"JavaScript Ultimate",
		"jQuery",
		"Package Control",
		"Package Syncing",
		"PackageResourceViewer",
		"PHP Completions Kit",
		"php-snippets",
		"PHPUnit Completions",
		"QuoteHTML",
		"ScopeHunter",
		"SideBarEnhancements",
		"StringUtilities",
		"SublimeLinter",
		"SublimeLinter-jshint",
		"SublimeLinter-phpcs",
		"Super-Awesome Paste",
		"SyncedSideBar",
		"Syntax Highlighting for Sass",
		"Text Pastry",
		"Vuejs Complete Package",
		"WordPress",
		"WordPress Customizer"
	]
}</pre>
</div>
</div>

**Comment by ihodev** [comment]
Can you try to disable colored title bar and check again?

`Command Palette › DA UI: Theme Settings`

```js
  "enable_title_bar_styling": false,
```

**Comment by swashata** [comment]
You sir are a genius. This has:

1. Resolved the issue with high CPU usage by SublimeText
2. Resolved the high CPU usage by mac WindowServer. I thought it was from sublimetext, but now I can confirm it.
3. Resolved another side effect. Previously sometimes, when I would fullscreen and then go back to normal screen, the titlebar would show up very weird (would overlap the tab section). It has resolved itself too.

Now the CPU usage doesn't spike to more than 10-15% with 20+ files open.

In the video it shows spike to 30-40% without the titlebar tweak, because I believe QuickTime was consuming more. When just using sublime, it reaches over 60%. But with the tweak, it stays within limit and the idle one stays at 2-3% or even less.

https://www.youtube.com/watch?v=YqXU_c7a23c

I also see an update for Sublime Text. I will install it and get back to you.

**Comment by swashata** [comment]
Okay updated SublimeText to Build 3154. The issue is still there. When titlebar style is enabled, CPU is at 30-40%. Without titlebar style, CPU is at 10-15% max. Both tests done almost under same circumstances.

**Comment by ihodev** [comment]
Thanks for such detailed info 😉 So, yes, this is ST-related issue. It seems that ST doesn't like custom title bars with custom themes. Please report this issue here: https://github.com/SublimeTextIssues/Core/issues

**Comment by ihodev** [comment]
I think I'll disable custom colored title bars by default with the next release.

**Comment by swashata** [comment]
Just did. And I think it would be best to have it disabled until sublime fixes it.

**Comment by wbond** [comment]
@swashata Are you able to reproduce this issue on a clean install with just DA UI installed?

I'm trying to reproduce the issue. It seems from reports that some users are hit by high CPU usage with Material and DA UI, but not Adaptive. However, it doesn't seem to be all users, and I seem to be one of the user that isn't affected.

I am wondering if there is some package that is causing the settings to be modified regularly, causing the theme to be re-set (or something similar?). See settings located in a theme cause the theme engine to track which settings affect the theme, and whenever a setting is changed we check to see if it is one of the settings that affects the current theme.

The custom title bars involve a number of API calls on NSWindow, and my hunch is that the theme calling the function that sets the custom title bar is causing the issue somehow. Unfortunately I really need to reproduce the error before I can realistically make a fix.

**Comment by swashata** [comment]
@wbond I will try by deactivating all add-ons and get back to you. Do you think I can somehow help with some sort of debug trace when the CPU usage is high?

**Comment by swashata** [comment]
@wbond So here's what I did.

1. Disable all packages while keeping DA CS and DA UI turned on. With DA UI, I have the custom titlebar enabled. Result is high CPU usage.

![sublime-diagnosis-1](https://user-images.githubusercontent.com/1623381/32821571-1b64bbc6-c9fa-11e7-8d67-03a35260cd0b.png)

2. I closed by open project files, keeping a blank window open. Now CPU usage at around 10%

![sublime-diagnosis-3](https://user-images.githubusercontent.com/1623381/32821610-4b73f5fc-c9fa-11e7-8e6d-c23443707647.png)

3. Disabled titlebar color in DA UI settings, while keeping all packages disabled. CPU down to 8% (and lower in some more time).

![sublime-diagnosis-4](https://user-images.githubusercontent.com/1623381/32821626-6691c08a-c9fa-11e7-8521-bc0b077d85ba.png)


I will try installing a fresh version in a different account and see if I can reproduce it.

**Comment by acheronfail** [comment]
FWIW I'm also seeing this issue. I'll try it out on a clean install with just DA UI and give an update here.

For the time being, my machine details:

* macOS 10.13.3
* Sublime Build 3157

**Comment by acheronfail** [comment]
Okay, the high CPU also occurs with a completely clean installation of Sublime Text, I can reproduce with these steps:

1. Use fresh installation of Sublime
2. Install Package Control
3. Install DA UI
4. UI: Select Theme -> DA UI
5. Open Preferences
6. View -> Add Folder to Project
7. CPU usage is now high

I found that adding a folder to the sidebar immediately increased CPU (no - it's not indexing the folder. I added a folder with 5 small text files in it). Sublime Text's CPU usage increases to ~ 25% immediately, and is matched by WindowServer (this issue seems to make both use somewhat equal amounts of CPU).

**Comment by acheronfail** [comment]
> I am wondering if there is some package that is causing the settings to be modified regularly, causing the theme to be re-set (or something similar?). See settings located in a theme cause the theme engine to track which settings affect the theme, and whenever a setting is changed we check to see if it is one of the settings that affects the current theme.

@wbond I'm not convinced this is the cause of a package (except maybe `DA UI`) since I can consistently reproduce high CPU usage with clean installs (only `PackageControl` and `DA UI` installed).

**Comment by wbond** [comment]
@acheronfail if the cpu usage is when you add a folder it is almost certainly the indexer. Check the status from the help menu.

**Comment by swashata** [comment]
I have checked too. If it was the indexer, then even disabling the color title bar would not have corrected the CPU usage. But when I disabled the color title bar, it got all fixed.

It could be because DA UI allows changing fonts of sidebar? Or something like this?

/cc @ihodev @wbond @acheronfail

**Comment by ihodev** [comment]
> it's not indexing the folder. I added a folder with 5 small text files in it, and I checked the indexing status, none are running

@wbond I don't think that this is index-related stuff.

> It could be because DA UI allows changing fonts of sidebar?

I don't think so too.

DA UI does nothing more than Adaptive theme, the only difference it doesn't provide `file_dark` & `file_medium` attributes.

**DA.sublime-theme**

```
  {
    "class": "title_bar", 
    "bg": [
      "background", 
      0, 
      0, 
      0, 
      0.1
    ], 
    "fg": [
      "background", 
      255, 
      255, 
      255, 
      0.65
    ]
  }, 
  {
    "class": "title_bar", 
    "attributes": [
      "file_light"
    ], 
    "fg": [
      "background", 
      0, 
      0, 
      0, 
      0.65
    ]
  }
```

**Adaptive.sublime-theme**

```
    {
        "class": "title_bar",
        "fg": ["background", 255, 255, 255, 0.7],
        "bg": ["background", 0, 0, 0, 0.4]
    },
    {
        "class": "title_bar",
        "attributes": ["file_dark"],
        "bg": ["background", 255, 255, 255, 0.15]
    },
    {
        "class": "title_bar",
        "attributes": ["file_medium"],
        "bg": ["background", 0, 0, 0, 0.2]
    },
    {
        "class": "title_bar",
        "attributes": ["file_light"],
        "fg": ["background", 0, 0, 0, 0.7],
        "bg": ["background", 0, 0, 0, 0.1]
    },
```

**Comment by wbond** [comment]
There are so many people saying so many things.

Can someone confirm that a clean start of Sublime Text with DA UI on build 3157 has 25%+ CPU usage while not indexing?

**Comment by wbond** [comment]
Just for reference, we found a bug on Mac with themes that have a themed title bar, and fixed it in build 3157. It could result in heavy CPU usage, and was related to using the themed title bar and a GPU switch. However, I haven't had any other reports of heavy CPU usage related to themes on 3157. Hence, since @acheronfail said they were getting heavy CPU usage on 3157 by adding a folder, that implies to me it is the indexer.

If you are running the Adaptive theme, or DA UI on a build less than 3157 on a Mac, you are bound to run into CPU issues when your machine switches GPUs. This is because something about the NSOpenGLView doesn't switch renderers when using a full-size content view (which allows us to draw behind a transparent title bar). Instead, the OS shuffles OpenGL commands and textured between the GPUs through main memory, which seems to manifest itself as increased CPU usage.

**Comment by acheronfail** [comment]
@wbond I said in my comment above that I already had checked the indexing status - I have done so time and time again to ensure this isn’t an indexing issue. 

For the record, this can be observed when the sidebar has opened a _completely_ empty directory as well. 

**Also note** that this does not occur when using the Adaptive theme. 

**And** each time Sublime’s CPU usage increases WindowServer’s does as well - exactly to match. 

I’ve also left Sublime open (taking steps as in my above comment) for the 8 hours since my last comment, and the CPU usage hasn’t dropped below 25%.

**Comment by wbond** [comment]
@acheronfail I did not catch the part that you checked indexing. Thanks for confirming. I will try to reproduce on my end. Unfortunately I do not have 10.13 available, but I will try to reproduce on 10.12.

**Comment by acheronfail** [comment]
@wbond If it's any help I just tried it inside a VM running 10.11, and the CPU didn't go above 5%.

**Comment by wbond** [comment]
Unfortunately I can't reproduce results anything like 25% CPU usage, even combined between Sublime Text and the window server. I've tried the Default, Adaptive and DA themes.

Right now I have the DA theme enabled with themed title bars. Sublime Text is using 1.5% of my CPU and Window Server about 5% with Sublime Text focused (cursor blinking). I have a number of folders opened (probably 200k+ files present). Even expanding a project with 50k+ files the CPU is still the same.

**Comment by wbond** [comment]
This machine is a 2013 15" rMBP that has had 10.9, 10.10, 10.11 and 10.12 upgraded since I bought it, but never a fresh install. I have all sorts of applications running, including various helpers (like Spectacle and Karabiner Elements).

There is obviously some other aspect. Perhaps Apple did something drastic to NSOpenGLView in 10.13?

Unfortunately I can't reasonably upgrade this machine. The 10.11 -> 10.12 upgrade messed up my cursor on my external 4k, and I'm not willing to sacrifice a couple of days to rebuilding my machine if 10.13 has more bugs on this hardware.

**Comment by wbond** [comment]
Honestly, it is weird that it would manifest itself on DA, but not the Adaptive theme. Anything that uses the themed title bar is going to trigger the same NSWindow changes necessary to draw behind a transparent title bar.

**Comment by acheronfail** [comment]
Yeah to me this definitely sounds like a High Sierra issue in 10.13 - especially since we can't reproduce the issue in anything lower. There are a few 10.12 machines at my work - I'll try and see if I can reproduce it on those and report back here. 👍

**Comment by wbond** [comment]
Do you have multiple GPUs in your laptop? Have you tried messing around with gfxCardStatus to see if dedicated vs integrated makes a difference?

**Comment by acheronfail** [comment]
In the laptop I'm using I don't, but I have a 10.13 laptop with a GPU in it at work - I'll try with that and gfxCardStatus and let you know.

**Comment by acheronfail** [comment]
Make sure you're restarting Sublime each time you test it - when the CPU increases, it stays consistently high _until I restart Sublime_, even if I disable the titlebar styling. But if it starts with the titlebar unstyled then the CPU usage is low.

Results from various machines (all running Sublime Text 3157):

* (10.13.3) MacBook Pro (15-inch, 2017) with GPU
    * **With GPU**: Sublime CPU: 5-15%, WindowServer 10-20%.
    * **Without GPU: Sublime CPU: 25-35%, WindowServer 25-35%.
* (10.13.3) MacBook Pro (13-inch, 2016)
    * Sublime CPU: 25-35%, WindowServer 25-35%.
* (10.12) MacBook Pro (15-inch, 2016) with GPU
    * **With GPU**: **Net yet tested, will update when I can**
    * **Without GPU**: **Net yet tested, will update when I can**
* (10.11) VM
    * No abnormalities.

**Comment by acheronfail** [comment]
@wbond okay I managed to find some machines running 10.12.

* `(10.12) MacBook (12-inch, 2015)`
    * Sublime CPU: 4-7%, WindowServer: 8-12%
* `(10.12) MacBook Pro (13-inch, 2016)`
    * Sublime CPU: 3-5%, WindowServer: 6-10%

I also had the opportunity to test this one several other machines running 10.13, and each time Sublime and WindowServer consistently use a heap of CPU.

**Comment by swashata** [comment]
@wbond I think there are some things apple changed with 10.13 possibly APFS file system and Metal 2 for GPU. When I first upgraded, my Adobe Suite almost stopped working, giving me and many others [this error](https://helpx.adobe.com/illustrator/kb/illustrator-and-mac-os-high-sierra.html). Since then I have switched to Affinity Designer because that is what my graphics team uses.

So maybe this problem is related to APFS or the new GPU rendering? (Metal 2)?

**Comment by acheronfail** [comment]
@wbond @swashata Good news! I just upgraded to `10.13.4`, and I can no longer reproduce this issue!

I'll try on another few different machines on `10.13.4` and make sure I'm not mistaken. @swashata if you could give this a try when you update that would be great.

**Comment by Lykegenes** [comment]
I'm still experiencing the issue on `10.13.4` and build `3160`. I have a 2012 retina MBP with GPU.
`10.13.4` fixed many small issues (mostly graphical stuttering and lag) on many apps, but this current issue is still present.

**Comment by acheronfail** [comment]
Okay, @Lykegenes is right. I don't know what happened, but shortly after I updated things seemed alright and it didn't look like this was happening. But I can still reproduce high CPU on `10.13.4`. 😞 

@Lykegenes how are you reproducing this? I'm still trying to see if I can find a more specific trigger than the steps above.

**Comment by swashata** [comment]
@acheronfail and @Lykegenes what is your filesystem? APFS?

**Comment by acheronfail** [comment]
@swashata yep, APFS.

**Comment by swashata** [comment]
This could be the issuing factor. Because adobe illustrator had very [similar issue](https://www.macrumors.com/2017/09/29/adobe-illustrator-indesign-macos-high-sierra/) with gfx rendering on APFS.

I wish I could test with legecy file system on 10.13, but sadly I just can not format right now :(

**Comment by acheronfail** [comment]
I'm starting to think that this isn't to do with styling the titlebar... I've had `"enable_title_bar_styling": false` (normal, unstyled titlebars) for a long time and the CPU is still high - eating up all my battery when I'm using Sublime. 😞 

Still trying to figure out exactly when the CPU starts getting high... 🤔

**Comment by swashata** [comment]
@acheronfail after setting `"enable_title_bar_styling": false` did you restart sublime? Like quit (cmd+Q) then run again.

**Comment by acheronfail** [comment]
@swashata Yep. I sure have (just did it again then as well). Still getting high CPU usage. 

I've also noticed that the usage stacks per window (ie, if you have 4 windows, CPU usage can be over 70%, etc).

**Comment by ihodev** [comment]
@acheronfail That's really strange 😞 

> I've also noticed that the usage stacks per window (ie, if you have 4 windows, CPU usage can be over 70%, etc).

Even with Default theme?

**Comment by acheronfail** [comment]
No - this doesn't occur with the default theme - maybe there's an odd configuration somewhere in DA UI?

**Comment by Lykegenes** [comment]
@swashata I'm using APFS too

@acheronfail simply setting `"enable_title_bar_styling": true` without even restarting Sublime triggers it for me. But if I want to stop the high CPU usage, I need to set it back to false, wait for it to be applied, and then restart Sublime.
Back in December or January, I reproduced this with a clean install of Sublime, with only Package Control and DA UI.

I just tested with multiple windows, as @acheronfail suggested, and here are my results 

with `"enable_title_bar_styling": false`:
* `1 window, 1 project opened`
  * Sublime CPU: 8-10%, WindowServer: 7-8%
* `5 windows, 5 projects opened`
  * Sublime CPU: 15-20%, WindowServer: 10-15%

with `"enable_title_bar_styling": true`:
* `1 window, 1 project opened`
  * Sublime CPU: 20-30%, WindowServer: 20-30%
* `5 windows, 5 projects opened`
  * Sublime CPU: 60-70%, WindowServer: 45-50%

In both cases, when I start with 1 window, open 4 more and then close them, the CPU usage drops to the same level as the beginning. Closing the extra windows seems to free the CPU usage taken by this window.


Allright, so this made me think about another test case. Here's my process to reproduce it : 
1. Open Sublime, and set `"enable_title_bar_styling": true` (Sublime CPU: 20-30%, WindowServer: 20-30%)
2. Close all the windows, **without quitting Sublime**. It should still show up in your dock and/or OSX top menu bar (Sublime CPU: 0-1%, WindowServer: 0-1%)
3. Open a new Sublime window. For me, it is a blank page. (Sublime CPU: 0-1%, WindowServer: 0-1%)
4. Open a project. (Sublime CPU: 20-30%, WindowServer: 20-30%)

The interesting part is step 3, where the title bar styling is set to true, but the CPU usage only goes up when I actually open a file or project!

I hope this can help, and hopefully @acheronfail might be able to reproduce this...

**Comment by acheronfail** [comment]
Here's a recording of reproducing it in a clean installation of Sublime.
Details:

* macOS 10.13.4
* Sublime 3161

Unfortunately GitHub doesn't support attaching video, but you can watch it here on Dropbox: https://www.dropbox.com/s/wlaoun0r3jrp25b/sublime-cpu.mp4?dl=0

**Things to note:**

* I cut the video short because of size, but the CPU usage stays *consistently high* forever. Not ever dropping below 19%.
* I just did this in a simple way (with Activity Monitor, etc) to show Sublime's CPU. I've monitored the CPU with other tools and it's consistently high
* You can't see `WindowServer`, but that also has high CPU

I'm thinking it might be a combination of theme settings than just the titlebar, especially since opening the sidebar (even with an empty folder) starts it off every time.

If I open more windows in sublime, the CPU stacks.

This means I can no longer use Sublime Text on the train to work since due to this super high CPU it eats like 60% of my batter in 45minutes! 😞

**Comment by swashata** [comment]
For this and various other reasons I have moved to VSCode :( Although it is not as fast as sublime text, but the built-in intellisense for JS is really all what I need :)

**Comment by wbond** [comment]
@ihodev There will be a fix in the next build to prevent this in the future, but the cause of this is the `layer1` animation you have on `icon_folder_loading`. You don't use `layer1` for `icon_folder`, and so the code running the animation continues.

We implicitly reset properties to their defaults, causing the opacity to be set to 0, but weren't cancelling a running animation. The Default and Adaptive themes didn't run into this since they only use `layer0` for both `icon_folder_loading` and `icon_folder`, and so the texture on `icon_folder` resets the animation from `icon_folder_loading`.

**Comment by ihodev** [comment]
@wbond Wow, thanks! Good catch!

**Comment by acheronfail** [comment]
@wbond any reason why this wouldn’t occur on 10.12 but it then would on 10.13?

**Comment by wbond** [comment]
That isn't clear to us. Jon's guess was that APFS is slower for folder scanning? 🙂

It required that the folder loading animation run. If you took an existing window and switched themes, the folders were already "loaded", so the animation wouldn't run. At fresh startup, often the folder will be scanned before the UI renders. Opening a window and adding a folder that isn't instantaneous to scan seems to be the way to reproduce.

**Comment by acheronfail** [comment]
FWIW I just finished creating a separate partition, and installing APFS and HFS with 10.13 and didn’t notice much differences between them. 

I also noticed that CPU increases with the Material theme as well. 

But installing 10.12 on the partition and then trying it there results in a fairly lower amount of CPU usage, so I’m not sure why 10.13 would use so much more?

🤷‍♂️

**Comment by wbond** [comment]
Yes, I do have a feeling that the fix for this will likely help with the various reports of the Material theme being a CPU hog. I seem to recall that theme using a lot of animations also.

**Comment by acheronfail** [comment]
I’ll upload my results (screenshots of CPU usage on both filesystems) so you can have a look once my computer finishes re-installing 👍

**Comment by acheronfail** [comment]
Ugh! The High Sierra installer automatically converts my HFS partition to APFS, and I can't get around it unless I make modifications to the "Install High Sierra.app". So really I only have some nice tests of 10.13.4 on APFS 😒 

I think they're useful anyway, since the titlebar styling does affect it: the CPU is highly increased when it's enabled (both with DA UI and Material).

In any case, here's some results for 10.13.4 APFS: https://www.dropbox.com/sh/eyx88ri2355jqoz/AADwXBKZayvh0SIKobqCcvVaa?dl=0 you've got two screenshots per test that I performed. Notice the CPU differences between styled titlebars.

@wbond Hope these can provide some insight.
Also I'm more than happy to reformat/test on other versions/filesystems - whatever you need 🙂

**Comment by wbond** [comment]
@acheronfail The increased CPU usage with a themed title bar and the animation bug doesn’t surprised me. To get the themed title bar, we have to use a full-size content view, which automatically switches the NSView for the content to layer-backed. I forget all of the details for what macOS does behind the schemes when a view is layer-backed, but it would appear it has to do some more shuffling.

Since the adaptive theme has low CPU usage with the themed title bar, we should be good once the theme is fixed, or the next dev release is cut.

**Comment by acheronfail** [comment]
@wbond awesome, thanks. I really appreciate that you and Jon sweat the details of this app, you guys are seriously the best! 👍 💯 🔥 

If you ever need anything tested, I'm more than happy to offer any assistance. 🙂

**Comment by swashata** [comment]
Awesome... I will try out Sublime with the updated theme or next dev release (which ever comes first) and let you all know.

**Comment by acheronfail** [comment]
Sublime 3162 is out - and this issue is fixed for me! 🎉

**Comment by acheronfail** [comment]
@swashata want to close this issue if it's been fixed? 🙂

**Comment by swashata** [comment]
Yeah sure... Just pinging @ihodev We can consider this resolved now.. 🍻

**Comment by ihodev** [comment]
🎉 @acheronfail @swashata @wbond Thanks guys!
