### ISSUE TITLE
Command Palette looks broken in build 3154

### ISSUE THREAD

**Issue by adrianpacala** [ihodev/sublime-da-ui#32]
Hi! First of all thanks for making this theme, it looks great 💞

ST3 build 3154 introduced a new command palette and it looks like it broke all existing UI themes (e.g. here's the same issue in [Monokai Pro](https://github.com/Monokai/monokai-pro-sublime-text/issues/53)).

It currently looks like this:

![screen shot 2017-11-19 at 10 30 09](https://user-images.githubusercontent.com/9934/32989793-03e41302-cd15-11e7-8712-f44e06f145c9.png)

**Comment by ihodev** [comment]
@adrianpacala Hi! Unfortunately, that's ST issue. See [this](https://forum.sublimetext.com/t/dev-build-3154/33286/35) for details.

**Comment by adrianpacala** [comment]
Fixed in build [3155](https://www.sublimetext.com/3dev) ✨✨✨
![screen shot 2017-11-30 at 08 54 59](https://user-images.githubusercontent.com/9934/33422089-4bc13b56-d5ac-11e7-9b72-7d3791874cd8.png)
