### ISSUE TITLE
How to change editor font? Question coming from Boxy.

### ISSUE THREAD

**Issue by spacesuitdiver** [ihodev/sublime-da-ui#34]
Hello,

In Boxy I was able to install a separate package to change the editor font, I noticed in another issue #27 that this seems to be still possible. I would gladly help write some of the documentation to include instructions for this.

Also,
Will DA UI eventually have many of the dialogs to edit the options without editing the settings json or is this one of the features that became unwieldy to maintain so it will be dropped?

Thanks for making Sublime great. :)

**Comment by swashata** [comment]
Hi,

To change editor font, open command pallet and type `DA UI: Theme Settings`. Now add or replace the following config:

```json
"font_face": "Operator Mono SSm Light"
```

PS: My whole config looks like this

```json
{
	"accent_color": "#ffcc66",
	"font_face": "Operator Mono SSm Light",
	"skin":
	{
		"id": "origin",
		"settings":
		{
		}
	},
	"enable_title_bar_styling": false,
}
```

Bdw, do you have title bar styling to true and does it give random high cpu usage? #30

**Comment by LeBlaaanc** [comment]
Thank you @swashata I do have it enabled and I haven't noticed any high CPU use, I just toggled it to see if there is any difference. My Sublime however does crash often now but usually due to indexing it seems.

**Comment by ihodev** [comment]
> Will DA UI eventually have many of the dialogs to edit the options without editing the settings json or is this one of the features that became unwieldy to maintain so it will be dropped?

I'm still thinking on it. I have some ideas how to implement UI for changing some basic settings, however due to lack of time it's still just an idea.
