### ISSUE TITLE
can't install: HTTP exception InvalidCertificateException error

### ISSUE THREAD

**Issue by olets** [ihodev/sublime-da-ui#39]
When I try to install DA UI I get an error:

Modal:

```
Package Control

Unable to download DA UI. Please view the console for more details.
```

Console:

```
ignored packages updated to: ["DA UI", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://github.com/ihodev/sublime-da-ui/releases/download/v1.0.0-beta.1.2/DAUI.sublime-package.
error: Package Control
```

This is on fresh Sublime install, macOS 10.12.6, sublime 3.0 build 3143

**Comment by ihodev** [comment]
@olets I think that's Package Control related issue.

**Comment by olets** [comment]
Ah, yes. Thanks
https://github.com/wbond/package_control/issues/1334

**Comment by iamanewbie** [comment]
Hi,
Facing the same problem here. Is there a proposed solution to this?
Thank You

**Comment by acheronfail** [comment]
It sure is a package control related issue - I found the fix here: https://github.com/wbond/package_control/issues/1220

Basically, it's an issue with the way some certificates are handled, I fixed it by using `curl` as the default downloader for package control.

Select `Preferences: Package Control Settings - User` from the command palette, and add:

```js
// I'm in Linux, so I moved "curl" to the start, but change for your OS.
"downloader_precedence": {
	"linux": [
		"curl",
		"wget",
		"urllib"
	],
	"osx": ["urllib"],
	"windows": ["wininet"]
},
// ...
```

**Comment by iamanewbie** [comment]
@acheronfail 
Ah, excellent!

I am on OSX and moving curl to the beginning fixed the issue. Thanks a lot.

**Comment by olets** [comment]
Copying over a note from wbond for anyone using the `downloader_precendence` workaround

>  Please don't do this. If for some reason you must, please be sure to erase these settings after I release the next version of Package Control.

(https://github.com/wbond/package_control/issues/1334#issuecomment-369153563)

**Comment by acheronfail** [comment]
FWIW - this seems to have been fixed for me on macOS in Sublime Build 3158. 😄
