### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by djmtype** [ihodev/sublime-da-ui#42]
Installing DA UI via package manager returns an alert: Unable to download DA UI. Please view the console for more details.

## Expected Behavior

DA UI should be installed.

## Current Behavior

DA UI fails to install. Returns error message to the console. 
"Error downloading package. HTTP exception InvalidCertificateException (Host github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://github.com/ihodev/sublime-da-ui/releases/download/v1.0.0-beta.1.2/DAUI.sublime-package."

## Your Environment

Running a fresh install of Sublime Text 3.0 Build 3143 on Mac OS 10.13.3. The only other plugins I have installed are A File Icon and Sass Syntax Highlighting. Tried with both plugins disabled, too.

**Comment by ihodev** [comment]
Please, see #39 & #40. Your problem is fixed in the latest ST dev version.
